import { data, type LoaderFunctionArgs, type MetaFunction } from "react-router";
import { getInstance } from "~/middleware/i18next";
import type { Route } from "./+types/licence";

export async function loader({ context }: LoaderFunctionArgs) {
    let i18n = getInstance(context);
    return data({
        title: i18n.t("home:title"),
    })
}

export function meta({ loaderData }: Route.MetaArgs) {
    const title = 'License & Data Sources' + ' - ' + loaderData.title
    return [
        { title },
        { property: "og:title", content: title },
        { property: "twitter:title", content: title },
    ]
}

const LicencePage = () => {
    return (
        <div className="m-auto max-w-4xl px-4 sm:px-6 py-4 sm:py-8 font-pretendard">
            {/* Main content card */}
            <div className="bg-white dark:bg-neutral-800 rounded-2xl shadow-lg border border-neutral-200 dark:border-neutral-700 p-8 md:p-12 z-10 relative">

                {/* Simple and clean page title */}
                <h1 className="text-3xl md:text-4xl font-bold text-neutral-800 dark:text-white mb-8 border-b border-neutral-300 dark:border-neutral-600 pb-4">
                    License & Data Sources
                </h1>

                {/* Section: Data Copyright */}
                <section className="mb-10">
                    <div className="mt-4 p-4 bg-blue-50 border-l-4 border-blue-500 text-blue-800 dark:bg-blue-900/30 dark:border-blue-400 dark:text-blue-200 rounded-md">
                        <h3 className="font-bold text-lg mb-2">Notice</h3>
                        <p>
                            All copyright of <a href='https://bluearchive.jp/' target="_blank" rel="noopener noreferrer"><b className='hover:underline'>"Blue Archive"</b></a> belongs to <a href='https://www.nexon.com' target="_blank" rel="noopener noreferrer"><b className='hover:underline'>NEXON Korea Corp.</b></a>, <a href='https://www.nexongames.co.kr/' target="_blank" rel="noopener noreferrer"><b className='hover:underline'>NEXON GAMES Co., Ltd.</b></a>, and <a href="https://www.yo-star.com" target="_blank" rel="noopener noreferrer"><b className='hover:underline'>YOSTAR, Inc.</b></a>
                        </p>
                    </div>


                </section>
                <section className="mb-10">

                    <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Data</h2>

                </section>

                {/* Section: Icons & Images */}
                <section className="mb-10">
                    <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Icons & Images</h2>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 mt-4 pl-2">
                        <li><b>Site logo, Star level icon:</b> Written by myself referring to the game asset</li>
                        <li><b>Student Portraits, In-Game Item Icons:</b> <a href="https://schaledb.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Schale DB</a></li>
                        <li><b>Teran Icon:</b> Traced game assets by myself</li>
                        <li><b>Others:</b> <a href="https://https://github.com/react-icons/react-icons/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">React Icons</a> or Generated by LLM</li>
                    </ul>
                </section>

                <section className="mb-10">
                    <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Data Sources</h2>

                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Total Assault Overall</h3>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li><b>S47-S76:</b> <a href="https://storage.googleapis.com/info.herdatasam.me" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Someone's Google Storage API</a></li>
                        <li><b>S77-S80:</b> <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Plana Stats</a></li>
                        <li><b>S81:</b> Provided by an anonymous data contributor</li>
                        <li><b>S82:</b> <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Plana Stats</a></li>

                    </ul>
                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Total Assault Teams</h3>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li><b>S47-S80:</b> <a href="https://arona.ai/raidreport" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Arona.AI Total Assault Report</a></li>
                        <li><b>S81-S82:</b> <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Plana Stats</a></li>
                    </ul>
                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Grand Assault Overall</h3>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">

                        <li><b>S1-S21:</b> <a href="https://storage.googleapis.com/info.herdatasam.me" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Someone's Google Storage API</a></li>
                        <li><b>S22-S25:</b> <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Plana Stats</a></li>
                        <li><b>S26-S27:</b> Provided by an anonymous data contributor</li>
                    </ul>
                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Grand Assault Teams</h3>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li><b>S1-S24:</b> <a href="https://arona.ai/eraidreport" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Arona.AI Grand Assault Report</a></li>

                        <li><b>S25-S27:</b> <a href="https://www.plana-stats.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Plana Stats</a></li>
                    </ul>

                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Japan Server Assault Live Data</h3>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li>Provided by an anonymous data contributor</li>

                    </ul>

                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Korea Server Assault Data</h3>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li>
                            Total Assault & Grand Assault Distribution Google Spreadsheets: <br />
                            <a href="https://docs.google.com/spreadsheets/d/1JGBeDCu8KtVIsWd4QbQhNJekeG1YD8ZmGmbfXYznT7k" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline break-all">docs.google.com/...</a>
                        </li>
                        <li>
                            Someone's Google Storage API: <br />
                            <a href="https://storage.googleapis.com/info.herdatasam.me" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline break-all">storage.googleapis.com/info.herdatasam.me</a>
                        </li>
                    </ul>

                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Student Matadata</h3>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li>
                            Student ID, Bullet Type, Alias, Position, Squad Type, Tactic Role, Academy:<br />
                            <a href="https://schaledb.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Schale DB</a>
                        </li>
                        <li>
                            Experience Tables:<br />
                            <a href="https://bluearchive.wiki/wiki/Experience_tables/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Blue Archive Wiki</a>
                        </li>
                    </ul>

                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Jukebox Data</h3>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li>
                            Base Data:<br />
                            <a href="https://arona.ai/jukebox/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Arona.AI BGM Player (Only Korean)</a>
                        </li>
                        <li>
                            Title & Composer:<br />
                            <a href="https://bluearchive.wiki/wiki/Music/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Blue Archive Wiki</a>
                        </li>
                        <li>
                            Music Video:<br />
                            <a href="https://www.youtube.com/@mo2bluearchive/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">MO2 Youtube Channel</a>
                        </li>
                    </ul>
                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-6 mb-2">Event Data</h3>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li>
                            Base Data & Translation:<br />
                            <a href="https://schaledb.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Schale DB</a>
                        </li>
                    </ul>
                </section>

                {/* Section: References */}
                <section>
                    <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">References During Development</h2>
                    <ul className="list-disc list-inside space-y-2 text-neutral-600 dark:text-neutral-400 mt-4 pl-2">
                        <li><a href="https://bluearchive-torment.netlify.app/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">BA Torment</a></li>
                        <li><a href="https://hina.loves.midokuni.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Hina Loves Midokuni</a></li>
                        <li><a href="https://www.souriki-border.com/" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">そうりきボーダー</a></li>
                        <li>and various source codes found on GitHub.</li>
                    </ul>
                </section>

                {/* Section: License */}
                <section className="mt-10 mb-10">
                    <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Source Code License</h2>
                    <h3 className="text-lg font-semibold text-neutral-700 dark:text-neutral-200 mt-4 mb-2">This Website</h3>
                    <ul className="list-disc list-inside space-y-1 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li>Distributed under the MIT License.</li>
                        <li>
                            Source Code: <a href="https://github.com/bluekiseki/BA-mobilization-trends-public" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Github</a>
                        </li>
                        <li>For dependency licenses, please refer to the `package.json` in the source code.</li>
                    </ul>
                </section>

                <section className="mt-10 mb-10">
                    <h2 className="text-2xl font-bold text-neutral-800 dark:text-white mb-4">Bug Reports & Contact</h2>
                    <ul className="list-disc list-inside space-y-1 text-neutral-600 dark:text-neutral-400 pl-2">
                        <li>Please report to <a href="https://github.com/bluekiseki/BA-mobilization-trends-public/issues" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">Github issues</a>.</li>
                    </ul>
                </section>
            </div>
        </div>
    );
};

export default LicencePage;